application: djangae-skeleton
version: 1
runtime: python27
api_version: 1
threadsafe: yes

builtins:
- remote_api: on

handlers:
- url: /_ah/(mapreduce|queue|warmup).*
  script: application.application.wsgi.application
  login: admin

- url: /.*
  script: application.application.wsgi.application

skip_files:
- ^(.*/)?.*\.py[co]
- ^\.gaedata
